name: Build and Test C++ Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: arch-latest

    strategy:
      matrix:
        os: [ arch-latest ]
        cmake: [ '3.25.0' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update git submodules
        run: git submodule update --init --recursive

      - name: Install necessary dependencies
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm \
            base-devel \
            clang \
            cmake \
            git \
            ninja

      - name: Cache C++ dependencies
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            /var/cache/pacman/pkg/
            /app/cache/
          key: ${{ runner.os }}-deps-${{ hashFiles('**/pacman.conf') }}
          restore-keys: ${{ runner.os }}-deps-

      - name: Build the project using CMake
        run: |
          cmake --preset=Release .
